name: cou_login
version: 1.0.0
description: An angular component that encapsulates the functionality needed for the game's login system

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  angular:  ^4.0.0
  angular_forms: ^1.0.0
  firebase: ^4.4.0
  googleapis_auth: ^0.2.3
  service_worker: ^0.1.2
  transmit:
    git:
      ref: dart-1-backport
      url: git://github.com/ChildrenOfUr/transmit.git

transformers:
  - angular:
     entry_points:
        - lib/cou_login.dart
        - web/login_test.dart