name: cou_login
version: 1.0.0
description: An angular component that encapsulates the functionality needed for the game's login system

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular:  ^5.0.0
  angular_forms: ^2.0.0
  firebase: ^5.0.2
  googleapis_auth: "^0.2.6"
  service_worker: "^0.2.3"
  transmit:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/transmit.git

dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
