name: cou_login
version: 0.1.4
description: A polymer component that encapsulates the functionality needed for the game's login system

dependencies:
  browser: any
  angular: "^4.0.0+2"
  firebase: ">=0.5.0 <0.6.0"
  transmit:
    git:
      ref: master
      url: git://github.com/ChildrenOfUr/transmit.git
  cou_toolkit:
    git:
      ref: dart-2
      url: git://github.com/ChildrenOfUr/cou_toolkit.git

transformers:
- angular:
    entry_points: web/login.dart